<<<<<<< HEAD
import Link from 'next/link';
import menu from '@/lib/menu';
import ItemCard from '@/components/ItemCard';
import AdSlot from '@/components/AdSlot';
import AuthorBox from '@/components/AuthorBox';
export default function Home() { const popular = menu.items.slice(0,6); return <main><section className="hero"><div className="hero-inner"><p className="eyebrow">Independent café guide</p><h1>Find your next<br/>Au Bon Pain favorite.</h1><p className="lead">We make the menu easier to browse before you leave home: what sounds good, what pairs well, and which details are worth confirming at your local café.</p><div className="hero-actions"><Link className="button" href="/menu">Browse the menu</Link><Link className="button secondary" href="/locations">Find a café</Link></div></div></section><div className="container"><AuthorBox/><AdSlot/><section><div className="section-head"><div><p className="eyebrow">A few places to start</p><h2>Popular picks</h2></div><Link className="text-link" href="/menu">See all categories →</Link></div><div className="grid">{popular.map(item => <ItemCard key={item.slug} item={item}/>)}</div></section><AdSlot/><section className="info-band"><p className="eyebrow">Quick answers</p><h2>Plan the visit, then verify the details.</h2><div className="grid"><div><h3>Hours</h3><p>Au Bon Pain hours vary widely by café, especially in airports, hospitals, campuses, and malls.</p><Link className="text-link" href="/hours">Read hours guidance →</Link></div><div><h3>Dietary choices</h3><p>Look for vegetarian badges here, then confirm ingredients with the café when an allergy matters.</p><Link className="text-link" href="/nutrition">Nutrition notes →</Link></div><div><h3>Ordering</h3><p>Soups, sandwiches, and a drink make an easy lunch. We have a few ways to make the choice less noisy.</p><Link className="text-link" href="/ordering-tips">Ordering tips →</Link></div></div></section><section className="prose"><p className="eyebrow">A useful starting point</p><h2>What this site is, and what it is not</h2><p>AuBonPainMenu.us is an independent menu guide for people who want to browse calmly before ordering. We write our own descriptions and keep item details tied to a verification date. We do not publish made-up prices, calorie counts, store addresses, hours, ratings, or coupons. Menus and availability change by café, so the official Au Bon Pain site and the team at your café remain the final source.</p><p>For the official menu, nutrition information, offers, and store locator, visit <a className="text-link" href="https://www.aubonpain.com" rel="nofollow noopener">aubonpain.com ↗</a>.</p></section><AdSlot/></div></main>; }
=======
import Link from 'next/link';
import menu from '@/lib/menu';
import ItemCard from '@/components/ItemCard';
import AdSlot from '@/components/AdSlot';
import AuthorBox from '@/components/AuthorBox';
export default function Home() { const popular = menu.items.slice(0,6); return <main><section className="hero"><div className="hero-inner"><p className="eyebrow">Independent café guide</p><h1>Find your next<br/>Au Bon Pain favorite.</h1><p className="lead">We make the menu easier to browse before you leave home: what sounds good, what pairs well, and which details are worth confirming at your local café.</p><div className="hero-actions"><Link className="button" href="/menu">Browse the menu</Link><Link className="button secondary" href="/locations">Find a café</Link></div></div></section><div className="container"><AuthorBox/><AdSlot/><section><div className="section-head"><div><p className="eyebrow">A few places to start</p><h2>Popular picks</h2></div><Link className="text-link" href="/menu">See all categories →</Link></div><div className="grid">{popular.map(item => <ItemCard key={item.slug} item={item}/>)}</div></section><AdSlot/><section className="info-band"><p className="eyebrow">Quick answers</p><h2>Plan the visit, then verify the details.</h2><div className="grid"><div><h3>Hours</h3><p>Au Bon Pain hours vary widely by café, especially in airports, hospitals, campuses, and malls.</p><Link className="text-link" href="/hours">Read hours guidance →</Link></div><div><h3>Dietary choices</h3><p>Look for vegetarian badges here, then confirm ingredients with the café when an allergy matters.</p><Link className="text-link" href="/nutrition">Nutrition notes →</Link></div><div><h3>Ordering</h3><p>Soups, sandwiches, and a drink make an easy lunch. We have a few ways to make the choice less noisy.</p><Link className="text-link" href="/ordering-tips">Ordering tips →</Link></div></div></section><section className="prose"><p className="eyebrow">A useful starting point</p><h2>What this site is, and what it is not</h2><p>AuBonPainMenu.us is an independent menu guide for people who want to browse calmly before ordering. We write our own descriptions and keep item details tied to a verification date. We do not publish made-up prices, calorie counts, store addresses, hours, ratings, or coupons. Menus and availability change by café, so the official Au Bon Pain site and the team at your café remain the final source.</p><p>For the official menu, nutrition information, offers, and store locator, visit <a className="text-link" href="https://www.aubonpain.com" rel="nofollow noopener">aubonpain.com ↗</a>.</p></section><AdSlot/></div></main>; }
>>>>>>> 15b473b8448200c67420739b6263e97808d963ee
