<<<<<<< HEAD
import ContentPage from '@/components/ContentPage';import {FaqSchema} from '@/components/Schemas';
const faqs=[['Are you affiliated with Au Bon Pain?','No. AuBonPainMenu.us is an independent informational website.'],['Do you publish prices or calories?','Only when supplied and verified in menu.json. This launch dataset leaves them empty, so we link to official sources instead.'],['Are menus the same at every café?','No. Menu items, seasonal availability, hours, and service can vary by location.'],['Where should I check nutrition?','Use the official nutrition guide and ask the café team about current preparation.'],['Can I find an Au Bon Pain near me?','Use the official store locator. We do not publish unverified addresses.'],['Do you have coupon codes?','No. For official offers and e-club information, visit the Au Bon Pain website.']];
export const metadata={title:'Au Bon Pain Menu FAQ'};export default function FAQ(){return <ContentPage eyebrow="Straight answers" title="Frequently asked questions" intro={<p>These are the questions we would ask before making a café trip: what changes by location, where nutrition belongs, and how to tell independent guidance from an official source.</p>}><FaqSchema questions={faqs.map(([question,answer])=>({question,answer}))}/><section className="faq-list narrow">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section></ContentPage>}
=======
import ContentPage from '@/components/ContentPage';import {FaqSchema} from '@/components/Schemas';
const faqs=[['Are you affiliated with Au Bon Pain?','No. AuBonPainMenu.us is an independent informational website.'],['Do you publish prices or calories?','Only when supplied and verified in menu.json. This launch dataset leaves them empty, so we link to official sources instead.'],['Are menus the same at every café?','No. Menu items, seasonal availability, hours, and service can vary by location.'],['Where should I check nutrition?','Use the official nutrition guide and ask the café team about current preparation.'],['Can I find an Au Bon Pain near me?','Use the official store locator. We do not publish unverified addresses.'],['Do you have coupon codes?','No. For official offers and e-club information, visit the Au Bon Pain website.']];
export const metadata={title:'Au Bon Pain Menu FAQ'};export default function FAQ(){return <ContentPage eyebrow="Straight answers" title="Frequently asked questions" intro={<p>These are the questions we would ask before making a café trip: what changes by location, where nutrition belongs, and how to tell independent guidance from an official source.</p>}><FaqSchema questions={faqs.map(([question,answer])=>({question,answer}))}/><section className="faq-list narrow">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section></ContentPage>}
>>>>>>> 15b473b8448200c67420739b6263e97808d963ee
